services:
  database:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=${DB_NAME:-laravel-docker}
      - MYSQL_USER=${DB_USER:-user}
      - MYSQL_PASSWORD=${DB_PASS:-password}
      - MYSQL_ROOT_PASSWORD=${DB_PASS:-password_root}
      - TZ=${TZ:-Asia/Tokyo}
    volumes:
      - db:/var/lib/mysql
    ports:
      - ${DB_PORT:-3306}:3306
    restart: always
    networks:
      - app-network
  app:
    build:
      context: ./docker/php/
      args:
        - TZ=${TZ:-Asia/Tokyo}
    volumes:
      - ${SOURCE:-./src}:/work/app
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
      - ./docker/php/supervisord.conf:/etc/supervisord.conf
      - ./docker/php/supervisord.d:/etc/supervisord.d
      # - ./docker/php/php-ini-overrides.ini:/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
    working_dir: /work/app
    environment:
      - PHP_IDE_CONFIG=serverName=localhost
    restart: always
    entrypoint: ["/usr/bin/supervisord", "-n", "-c",  "/etc/supervisord.conf"]
    networks:
      - app-network

  web:
    image: nginx:latest
    depends_on:
      - app
    container_name: project-web
    ports:
      - ${WEB_PORT:-8080}:80
    volumes:
      - ./src:/work/app
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ:-Asia/Tokyo}
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db: